name: Build and test workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: cli
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go get -v -t -d ./...
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Generate sbom
      run: |
        wget -qO- "https://github.com/spdx/spdx-sbom-generator/releases/download/v0.0.13/spdx-sbom-generator-v0.0.13-linux-amd64.tar.gz" | \
        tar xvz && \
        chmod +x spdx-sbom-generator
        ./spdx-sbom-generator --path .
      shell: bash

    - name: Create Snapshot
      uses: goreleaser/goreleaser-action@v3.1.0
      with:
        version: latest
        args: --snapshot --skip-publish --rm-dist
